title: Vohiyo Shiba
author: Chau (Xiaohong Zhu)
email: xzhu0706@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A shiba blog with shiba images.

# social links
instagram_username: iamchau
github_username:  xzhu0706

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
